# Generated by Django 5.2.7 on 2026-03-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0002_productstatus_profile_bank_account_profile_bank_ifsc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_vip',
            field=models.BooleanField(default=True),
        ),
    ]
