# Generated by Django 5.2.7 on 2026-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0003_alter_profile_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
