# Generated by Django 5.2.7 on 2026-03-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0005_alter_withdrawrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomedayrecord',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
